<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'role_id' => 3,
                'name' => 'Owner1',
                'password' => bcrypt('11223344'),
            ],
            [
                'role_id' => 3,
                'name' => 'Owner2',
                'password' => bcrypt('22334455'),
            ],
            [
                'role_id' => 3,
                'name' => 'Owner3',
                'password' => bcrypt('33445566'),
            ],
            [
                'role_id' => 3,
                'name' => 'Owner4',
                'password' => bcrypt('44556677'),
            ],
            [
                'role_id' => 1,
                'name' => 'Chinnakalayamuthur',
                'password' => bcrypt('12345678'),
            ],
            [
                'role_id' => 1,
                'name' => 'Neikkarapatti',
                'password' => bcrypt('23456781'),
            ],
            [
                'role_id' => 1,
                'name' => 'Andipatti',
                'password' => bcrypt('34567812'),
            ],
            [
                'role_id' => 1,
                'name' => 'Devmetals',
                'password' => bcrypt('45678123'),
            ],
            [
                'role_id' => 1,
                'name' => 'Kuthiriyar',
                'password' => bcrypt('56781234'),
            ],
            [
                'role_id' => 1,
                'name' => 'Vannamparai',
                'password' => bcrypt('67812345'),
            ],
            [
                'role_id' => 1,
                'name' => 'Ammapatti',
                'password' => bcrypt('78123456'),
            ],
            [
                'role_id' => 1,
                'name' => 'Kannivadi',
                'password' => bcrypt('81234567'),
            ],
            [
                'role_id' => 1,
                'name' => 'Reddiarpatti',
                'password' => bcrypt('87654321'),
            ],
            [
                'role_id' => 1,
                'name' => 'Gopalpatti',
                'password' => bcrypt('76543218'),
            ],
            [
                'role_id' => 1,
                'name' => 'Natham',
                'password' => bcrypt('65432187'),
            ],
            ['role_id' => 2, 'name' => 'chisup1',  'site_id' => 1,  'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup2',  'site_id' => 2,  'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup3',  'site_id' => 3,  'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup4',  'site_id' => 4,  'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup5',  'site_id' => 5,  'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup6',  'site_id' => 6,  'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup7',  'site_id' => 7,  'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup8',  'site_id' => 8,  'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup9',  'site_id' => 9,  'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup10', 'site_id' => 10, 'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup11', 'site_id' => 11, 'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup12', 'site_id' => 12, 'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup13', 'site_id' => 13, 'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup14', 'site_id' => 14, 'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup15', 'site_id' => 15, 'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup16', 'site_id' => 16, 'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup17', 'site_id' => 17, 'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup18', 'site_id' => 18, 'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup19', 'site_id' => 19, 'taluk_id' => 1],
            ['role_id' => 2, 'name' => 'chisup20', 'site_id' => 20, 'taluk_id' => 1],

            ['role_id' => 2, 'name' => 'neisup1',  'site_id' => 21,  'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup2',  'site_id' => 22,  'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup3',  'site_id' => 23,  'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup4',  'site_id' => 24,  'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup5',  'site_id' => 25,  'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup6',  'site_id' => 26,  'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup7',  'site_id' => 27,  'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup8',  'site_id' => 28,  'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup9',  'site_id' => 29,  'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup10', 'site_id' => 30, 'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup11', 'site_id' => 31, 'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup12', 'site_id' => 32, 'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup13', 'site_id' => 33, 'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup14', 'site_id' => 34, 'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup15', 'site_id' => 35, 'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup16', 'site_id' => 36, 'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup17', 'site_id' => 37, 'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup18', 'site_id' => 38, 'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup19', 'site_id' => 39, 'taluk_id' => 2],
            ['role_id' => 2, 'name' => 'neisup20', 'site_id' => 40, 'taluk_id' => 2],

            ['role_id' => 2, 'name' => 'andisup1',  'site_id' => 41,  'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup2',  'site_id' => 42,  'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup3',  'site_id' => 43,  'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup4',  'site_id' => 44,  'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup5',  'site_id' => 45,  'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup6',  'site_id' => 46,  'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup7',  'site_id' => 47,  'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup8',  'site_id' => 48,  'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup9',  'site_id' => 49,  'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup10', 'site_id' => 50, 'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup11', 'site_id' => 51, 'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup12', 'site_id' => 52, 'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup13', 'site_id' => 53, 'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup14', 'site_id' => 54, 'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup15', 'site_id' => 55, 'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup16', 'site_id' => 56, 'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup17', 'site_id' => 57, 'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup18', 'site_id' => 58, 'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup19', 'site_id' => 59, 'taluk_id' => 3],
            ['role_id' => 2, 'name' => 'andisup20', 'site_id' => 60, 'taluk_id' => 3],

            ['role_id' => 2, 'name' => 'devsup1',  'site_id' => 61,  'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup2',  'site_id' => 62,  'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup3',  'site_id' => 63,  'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup4',  'site_id' => 64,  'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup5',  'site_id' => 65,  'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup6',  'site_id' => 66,  'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup7',  'site_id' => 67,  'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup8',  'site_id' => 68,  'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup9',  'site_id' => 69,  'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup10', 'site_id' => 70, 'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup11', 'site_id' => 71, 'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup12', 'site_id' => 72, 'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup13', 'site_id' => 73, 'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup14', 'site_id' => 74, 'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup15', 'site_id' => 75, 'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup16', 'site_id' => 76, 'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup17', 'site_id' => 77, 'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup18', 'site_id' => 78, 'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup19', 'site_id' => 79, 'taluk_id' => 4],
            ['role_id' => 2, 'name' => 'devsup20', 'site_id' => 80, 'taluk_id' => 4],

            ['role_id' => 2, 'name' => 'kutsup1',  'site_id' => 81,  'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup2',  'site_id' => 82,  'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup3',  'site_id' => 83,  'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup4',  'site_id' => 84,  'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup5',  'site_id' => 85,  'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup6',  'site_id' => 86,  'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup7',  'site_id' => 87,  'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup8',  'site_id' => 88,  'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup9',  'site_id' => 89,  'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup10', 'site_id' => 90, 'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup11', 'site_id' => 91, 'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup12', 'site_id' => 92, 'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup13', 'site_id' => 93, 'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup14', 'site_id' => 94, 'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup15', 'site_id' => 95, 'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup16', 'site_id' => 96, 'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup17', 'site_id' => 97, 'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup18', 'site_id' => 98, 'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup19', 'site_id' => 99, 'taluk_id' => 5],
            ['role_id' => 2, 'name' => 'kutsup20', 'site_id' => 100, 'taluk_id' => 5],

            ['role_id' => 2, 'name' => 'vansup1',  'site_id' => 101,  'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup2',  'site_id' => 102,  'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup3',  'site_id' => 103,  'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup4',  'site_id' => 104,  'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup5',  'site_id' => 105,  'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup6',  'site_id' => 106,  'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup7',  'site_id' => 107,  'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup8',  'site_id' => 108,  'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup9',  'site_id' => 109,  'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup10', 'site_id' => 110, 'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup11', 'site_id' => 111, 'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup12', 'site_id' => 112, 'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup13', 'site_id' => 113, 'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup14', 'site_id' => 114, 'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup15', 'site_id' => 115, 'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup16', 'site_id' => 116, 'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup17', 'site_id' => 117, 'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup18', 'site_id' => 118, 'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup19', 'site_id' => 119, 'taluk_id' => 6],
            ['role_id' => 2, 'name' => 'vansup20', 'site_id' => 120, 'taluk_id' => 6],

            ['role_id' => 2, 'name' => 'ammsup1',  'site_id' => 121,  'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup2',  'site_id' => 122,  'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup3',  'site_id' => 123,  'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup4',  'site_id' => 124,  'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup5',  'site_id' => 125,  'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup6',  'site_id' => 126,  'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup7',  'site_id' => 127,  'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup8',  'site_id' => 128,  'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup9',  'site_id' => 129,  'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup10', 'site_id' => 130, 'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup11', 'site_id' => 131, 'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup12', 'site_id' => 132, 'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup13', 'site_id' => 133, 'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup14', 'site_id' => 134, 'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup15', 'site_id' => 135, 'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup16', 'site_id' => 136, 'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup17', 'site_id' => 137, 'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup18', 'site_id' => 138, 'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup19', 'site_id' => 139, 'taluk_id' => 7],
            ['role_id' => 2, 'name' => 'ammsup20', 'site_id' => 140, 'taluk_id' => 7],


        ];

        foreach ($data as $item) {
            User::create($item);
        }
    }
}
